export const ADD_ROW = 'ADD_ROW';
export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP';
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const PREFERENCES_CHANGED = 'PREFERENCES_CHANGED';




