export const ADD_ROW = 'ADD_ROW';
export const DELETE_ROW = 'DELETE_ROW';
export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP';
export const WINDOW_RESIZE = 'WINDOW_RESIZE';
export const INPUT_CHANGED = 'INPUT_CHANGED';
export const PREFERENCES_CHANGED = 'PREFERENCES_CHANGED';
export const GET_JOB_INFO = 'GET_JOB_INFO';
export const CLEAR_JOB_INFO = 'CLEAR_JOB_INFO';




